"use strict";
var express_1 = require("express");
var router = express_1["default"].Router();
var posts_1 = require("../controller/posts");
router.post("/signup", posts_1.signup);
router.get('/login', posts_1.login);
router.get('/user/:id/data', posts_1.ensureToken, posts_1.view);
router.post('/user/data', posts_1.ensureToken, posts_1.add);
router.put('/user/:id/data', posts_1.ensureToken, posts_1.update);
router.get('/user/:id/data', posts_1.ensureToken, posts_1.deactivate);
module.exports = router;
